### ISSUE TITLE
Show potential bay templates from `SITIPE` for a given Bay from SQL database

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-sitipe-service#5]
As a user of the SITIPE editor plugin I want to see all bay templates that can be added to a  Bay element. 

Requirements

add a playlist_add icon button to right upper corner

by clicking show a list with all possible bay templates

first get the assignedBayTypicals for a given version 1.00 like so SELECT assignedBayTypicals FROM [databasename].[dbo].[frameworkID_SYSTEM_VERSION_LIST] WHERE version="1.00" 

this is a point separated array of the different typical ID like so ID1.ID2.ID3 

for each of the given bay template IDs get the bay template name like so SELECT name FROM [databasename].[dbo].[frameworkID_BayTypicals_LIST_]

DataBase dependencies

frameworkID: this is a variable given once per user e.g. Alliander. I this story is is given as cf3 and is needed to query the proper as it is part of the table name like so SELECT ... FROM [databasename].[dbo].[frameworkID]. .... 

version: SITIPE is all around version control. This means that you can have multiple versions of everything in the data base. In this story the version is given as 1.00 . You can find the different version within SELECT version FROM [databasename].[dbo].[frameworkID_SYSTEM_VERSION_LIST]

**Comment by Sander3003** [comment]
Query

SELECT * FROM cf3__BayTypicals_LIST_
    WHERE accessId IN (
        SELECT VALUE FROM cf3__SYSTEM_VERSION_LIST_ CROSS APPLY STRING_SPLIT(assignedBayTypicals, ',')
        WHERE version = '1.00'
    );

**Comment by Sander3003** [comment]
We are allowed to share the Siemens example data in order to test it.

**Comment by Stef3st** [comment]
This has been merged. Closing the issue
